# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow3(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1150, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_camera = QtWidgets.QVBoxLayout()
        self.verticalLayout_camera.setSpacing(0)
        self.verticalLayout_camera.setObjectName("verticalLayout_camera")
        self.horizontalLayout_10.addLayout(self.verticalLayout_camera)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_7 = QtWidgets.QWidget(self.frame_5)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem = QtWidgets.QSpacerItem(450, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton = QtWidgets.QPushButton(self.widget_7)
        self.pushButton.setStyleSheet("#pushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_13.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"    border:none;\n"
"}\n"
"QPushButton#pushButton_2:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_13.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_3.setStyleSheet("#pushButton_3{\n"
"    border:none;\n"
"}\n"
"QPushButton#pushButton_3:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/simui-minmax.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_13.addWidget(self.pushButton_3)
        self.pushButton_1 = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_1.setStyleSheet("#pushButton_1{\n"
"    border:none;\n"
"}\n"
"QPushButton#pushButton_1:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.pushButton_1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_1.setIcon(icon3)
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout_13.addWidget(self.pushButton_1)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_13)
        self.verticalLayout_8.addWidget(self.widget_7)
        self.label_14 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_14.setFont(font)
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_8.addWidget(self.label_14)
        self.widget_8 = QtWidgets.QWidget(self.frame_5)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_3.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(20)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.widget_8)
        self.textBrowser_5.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.textBrowser_5.setFont(font)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.gridLayout_3.addWidget(self.textBrowser_5, 9, 1, 1, 2)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.widget_8)
        self.textBrowser_3.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.textBrowser_3.setFont(font)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.gridLayout_3.addWidget(self.textBrowser_3, 5, 1, 1, 2)
        self.label_midu = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_midu.setFont(font)
        self.label_midu.setAlignment(QtCore.Qt.AlignCenter)
        self.label_midu.setObjectName("label_midu")
        self.gridLayout_3.addWidget(self.label_midu, 6, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.widget_8)
        self.textBrowser_4.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.textBrowser_4.setFont(font)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.gridLayout_3.addWidget(self.textBrowser_4, 6, 1, 1, 2)
        self.label_zhuangtai = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_zhuangtai.setFont(font)
        self.label_zhuangtai.setAlignment(QtCore.Qt.AlignCenter)
        self.label_zhuangtai.setObjectName("label_zhuangtai")
        self.gridLayout_3.addWidget(self.label_zhuangtai, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_time = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_time.setFont(font)
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.gridLayout_3.addWidget(self.label_time, 9, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_tem = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_tem.setFont(font)
        self.label_tem.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tem.setObjectName("label_tem")
        self.gridLayout_3.addWidget(self.label_tem, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.widget_8)
        self.textBrowser_2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_3.addWidget(self.textBrowser_2, 3, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 8, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_camera = QtWidgets.QLabel(self.widget_8)
        self.label_camera.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_camera.setFont(font)
        self.label_camera.setAlignment(QtCore.Qt.AlignCenter)
        self.label_camera.setObjectName("label_camera")
        self.gridLayout_3.addWidget(self.label_camera, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.textBrowser_1 = QtWidgets.QTextBrowser(self.widget_8)
        self.textBrowser_1.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.textBrowser_1.setFont(font)
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.gridLayout_3.addWidget(self.textBrowser_1, 1, 1, 1, 2)
        self.textBrowser = QtWidgets.QTextBrowser(self.widget_8)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 50))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_3.addWidget(self.textBrowser, 8, 1, 1, 2)
        self.verticalLayout_8.addWidget(self.widget_8)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_start = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_start.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet("QPushButton#pushButton_start{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_start:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_start:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.gridLayout_2.addWidget(self.pushButton_start, 0, 0, 1, 1)
        self.pushButton_light = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_light.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_light.setFont(font)
        self.pushButton_light.setStyleSheet("QPushButton#pushButton_light{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_light:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_light:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_light.setObjectName("pushButton_light")
        self.gridLayout_2.addWidget(self.pushButton_light, 0, 2, 1, 1)
        self.pushButton_wash = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_wash.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_wash.setFont(font)
        self.pushButton_wash.setStyleSheet("QPushButton#pushButton_wash{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_wash:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_wash:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_wash.setObjectName("pushButton_wash")
        self.gridLayout_2.addWidget(self.pushButton_wash, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.pushButton_end = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_end.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_end.setFont(font)
        self.pushButton_end.setStyleSheet("QPushButton#pushButton_end{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_end:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_end:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_end.setObjectName("pushButton_end")
        self.gridLayout_2.addWidget(self.pushButton_end, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_2)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 3)
        self.verticalLayout_8.setStretch(2, 7)
        self.verticalLayout_8.setStretch(3, 4)
        self.horizontalLayout_10.addWidget(self.frame_5)
        self.horizontalLayout_10.setStretch(0, 6)
        self.horizontalLayout_10.setStretch(1, 4)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_qx = QtWidgets.QVBoxLayout()
        self.verticalLayout_qx.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_qx.setSpacing(0)
        self.verticalLayout_qx.setObjectName("verticalLayout_qx")
        self.horizontalLayout_6.addLayout(self.verticalLayout_qx)
        self.gridWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget.setStyleSheet("background-color: rgb(202, 202, 202);")
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar_cx = QtWidgets.QProgressBar(self.gridWidget)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.progressBar_cx.setFont(font)
        self.progressBar_cx.setStyleSheet("border-radius: 5px;                                \n"
"font: 25 14pt \"Malgun Gothic Semilight\";\n"
"text-align: center;")
        self.progressBar_cx.setProperty("value", 0)
        self.progressBar_cx.setObjectName("progressBar_cx")
        self.gridLayout.addWidget(self.progressBar_cx, 3, 1, 1, 1)
        self.progressBar_start = QtWidgets.QProgressBar(self.gridWidget)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.progressBar_start.setFont(font)
        self.progressBar_start.setStyleSheet("border-radius: 5px;                                \n"
"font: 25 14pt \"Malgun Gothic Semilight\";\n"
"text-align: center;\n"
"")
        self.progressBar_start.setProperty("value", 0)
        self.progressBar_start.setObjectName("progressBar_start")
        self.gridLayout.addWidget(self.progressBar_start, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.progressBar_yr = QtWidgets.QProgressBar(self.gridWidget)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.progressBar_yr.setFont(font)
        self.progressBar_yr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_yr.setStyleSheet("border-radius: 5px;                                \n"
"font: 25 14pt \"Malgun Gothic Semilight\";\n"
"text-align: center;")
        self.progressBar_yr.setProperty("value", 0)
        self.progressBar_yr.setObjectName("progressBar_yr")
        self.gridLayout.addWidget(self.progressBar_yr, 1, 1, 1, 1)
        self.horizontalLayout_6.addWidget(self.gridWidget)
        self.horizontalLayout_6.setStretch(0, 7)
        self.horizontalLayout_6.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout.setStretch(0, 7)
        self.verticalLayout.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_1.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_2.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_14.setText(_translate("MainWindow", "溶液结晶检测系统"))
        self.label_midu.setText(_translate("MainWindow", "密度："))
        self.label_zhuangtai.setText(_translate("MainWindow", "结晶状况："))
        self.label_time.setText(_translate("MainWindow", "时间："))
        self.label_tem.setText(_translate("MainWindow", "温度："))
        self.label.setText(_translate("MainWindow", "PH值:"))
        self.label_camera.setText(_translate("MainWindow", "摄像头序号："))
        self.pushButton_start.setText(_translate("MainWindow", "开始"))
        self.pushButton_light.setText(_translate("MainWindow", "灯光"))
        self.pushButton_wash.setText(_translate("MainWindow", "冲洗"))
        self.pushButton_end.setText(_translate("MainWindow", "结束"))
        self.label_2.setText(_translate("MainWindow", "预热:"))
        self.label_3.setText(_translate("MainWindow", "开始:"))
        self.label_4.setText(_translate("MainWindow", "冲洗:"))
import resource_rc
