# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_searching_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_data_search(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1160, 734)
        MainWindow.setStyleSheet("background-color: rgb(222, 222, 222);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_7 = QtWidgets.QWidget(self.centralwidget)
        self.widget_7.setStyleSheet("")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem = QtWidgets.QSpacerItem(450, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton = QtWidgets.QPushButton(self.widget_7)
        self.pushButton.setStyleSheet("#pushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_13.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"    border:none;\n"
"}\n"
"QPushButton#pushButton_2:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_13.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_3.setStyleSheet("#pushButton_3{\n"
"    border:none;\n"
"}\n"
"QPushButton#pushButton_3:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/simui-minmax.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_13.addWidget(self.pushButton_3)
        self.pushButton_1 = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_1.setStyleSheet("#pushButton_1{\n"
"    border:none;\n"
"}\n"
"QPushButton#pushButton_1:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.pushButton_1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_1.setIcon(icon3)
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout_13.addWidget(self.pushButton_1)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_13)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.data_source_labal = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.data_source_labal.setFont(font)
        self.data_source_labal.setAlignment(QtCore.Qt.AlignCenter)
        self.data_source_labal.setObjectName("data_source_labal")
        self.horizontalLayout.addWidget(self.data_source_labal)
        self.data_source = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.data_source.setFont(font)
        self.data_source.setObjectName("data_source")
        self.data_source.addItem("")
        self.data_source.addItem("")
        self.data_source.addItem("")
        self.data_source.addItem("")
        self.horizontalLayout.addWidget(self.data_source)
        spacerItem1 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.tem_limit_show = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.tem_limit_show.setFont(font)
        self.tem_limit_show.setAlignment(QtCore.Qt.AlignCenter)
        self.tem_limit_show.setObjectName("tem_limit_show")
        self.horizontalLayout.addWidget(self.tem_limit_show)
        self.tem_limit = QtWidgets.QDoubleSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tem_limit.setFont(font)
        self.tem_limit.setMaximum(160.0)
        self.tem_limit.setObjectName("tem_limit")
        self.horizontalLayout.addWidget(self.tem_limit)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.time_Layout = QtWidgets.QHBoxLayout()
        self.time_Layout.setObjectName("time_Layout")
        self.time_from_labal = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.time_from_labal.setFont(font)
        self.time_from_labal.setAlignment(QtCore.Qt.AlignCenter)
        self.time_from_labal.setObjectName("time_from_labal")
        self.time_Layout.addWidget(self.time_from_labal)
        self.s_datetime = QtWidgets.QDateTimeEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.s_datetime.setFont(font)
        self.s_datetime.setObjectName("s_datetime")
        self.time_Layout.addWidget(self.s_datetime)
        self.to_labal = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.to_labal.setFont(font)
        self.to_labal.setAlignment(QtCore.Qt.AlignCenter)
        self.to_labal.setObjectName("to_labal")
        self.time_Layout.addWidget(self.to_labal)
        self.e_datetime = QtWidgets.QDateTimeEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.e_datetime.setFont(font)
        self.e_datetime.setObjectName("e_datetime")
        self.time_Layout.addWidget(self.e_datetime)
        spacerItem3 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.time_Layout.addItem(spacerItem3)
        self.pushButton_all = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_all.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_all.setFont(font)
        self.pushButton_all.setStyleSheet("QPushButton#pushButton_all{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_all:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_all:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_all.setObjectName("pushButton_all")
        self.time_Layout.addWidget(self.pushButton_all)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.time_Layout.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.time_Layout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.pushButton_tem = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_tem.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_tem.setFont(font)
        self.pushButton_tem.setStyleSheet("QPushButton#pushButton_tem{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_tem:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_tem:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_tem.setObjectName("pushButton_tem")
        self.horizontalLayout_3.addWidget(self.pushButton_tem)
        spacerItem6 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.pushButton_density = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_density.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_density.setFont(font)
        self.pushButton_density.setStyleSheet("QPushButton#pushButton_density{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_density:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_density:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_density.setObjectName("pushButton_density")
        self.horizontalLayout_3.addWidget(self.pushButton_density)
        spacerItem7 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.pushButton_ph = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ph.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_ph.setFont(font)
        self.pushButton_ph.setStyleSheet("QPushButton#pushButton_ph{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_ph:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_ph:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_ph.setObjectName("pushButton_ph")
        self.horizontalLayout_3.addWidget(self.pushButton_ph)
        spacerItem8 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.pushButton_return = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_return.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_return.setFont(font)
        self.pushButton_return.setStyleSheet("QPushButton#pushButton_return{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_return:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_return:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_return.setObjectName("pushButton_return")
        self.horizontalLayout_3.addWidget(self.pushButton_return)
        spacerItem9 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sql_table_show = QtWidgets.QTableWidget(self.centralwidget)
        self.sql_table_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sql_table_show.setObjectName("sql_table_show")
        self.sql_table_show.setColumnCount(0)
        self.sql_table_show.setRowCount(0)
        self.verticalLayout.addWidget(self.sql_table_show)
        self.tem_limit_on_off = QtWidgets.QCheckBox(self.centralwidget)
        self.tem_limit_on_off.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tem_limit_on_off.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tem_limit_on_off.setObjectName("tem_limit_on_off")
        self.verticalLayout.addWidget(self.tem_limit_on_off)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.setStretch(5, 16)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.showMinimized) # type: ignore
        self.pushButton_1.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "溶液析晶检测系统记录查询"))
        self.data_source_labal.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">数据源:</p></body></html>"))
        self.data_source.setItemText(0, _translate("MainWindow", "01罐"))
        self.data_source.setItemText(1, _translate("MainWindow", "02罐"))
        self.data_source.setItemText(2, _translate("MainWindow", "03罐"))
        self.data_source.setItemText(3, _translate("MainWindow", "全部"))
        self.tem_limit_show.setText(_translate("MainWindow", "临界温度设置:"))
        self.time_from_labal.setText(_translate("MainWindow", "时间从:"))
        self.to_labal.setText(_translate("MainWindow", "到:"))
        self.pushButton_all.setText(_translate("MainWindow", "全部查询"))
        self.pushButton_tem.setText(_translate("MainWindow", "温度记录"))
        self.pushButton_density.setText(_translate("MainWindow", "密度记录"))
        self.pushButton_ph.setText(_translate("MainWindow", "PH值记录"))
        self.pushButton_return.setText(_translate("MainWindow", "返回"))
        self.tem_limit_on_off.setText(_translate("MainWindow", "单独查询临界温度以上数据"))
import resource_rc
