# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaceui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1355, 698)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 0, 1200, 700))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_1 = QtWidgets.QFrame(self.frame)
        self.frame_1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-top-right-radius:10px;")
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.widget_1 = QtWidgets.QWidget(self.frame_1)
        self.widget_1.setGeometry(QtCore.QRect(1070, 0, 121, 51))
        self.widget_1.setObjectName("widget_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.widget_1)
        self.pushButton.setStyleSheet("#pushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_1)
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"    border:none;\n"
"}\n"
"QPushButton#pushButton_2:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_1 = QtWidgets.QPushButton(self.widget_1)
        self.pushButton_1.setStyleSheet("#pushButton_1{\n"
"    border:none;\n"
"}\n"
"QPushButton#pushButton_1:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.pushButton_1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_1.setIcon(icon2)
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout_2.addWidget(self.pushButton_1)
        self.verticalLayout.addWidget(self.frame_1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255)；")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_main = QtWidgets.QWidget()
        self.page_main.setStyleSheet("")
        self.page_main.setObjectName("page_main")
        self.frame_2 = QtWidgets.QFrame(self.page_main)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1201, 561))
        self.frame_2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_3 = QtWidgets.QWidget(self.frame_2)
        self.widget_3.setObjectName("widget_3")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setGeometry(QtCore.QRect(170, 10, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("border-image:url(:/icons/icons/one .png)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_v1 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_v1.setGeometry(QtCore.QRect(50, 480, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_v1.setFont(font)
        self.pushButton_v1.setStyleSheet("QPushButton#pushButton_v1{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_v1:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_v1:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_v1.setObjectName("pushButton_v1")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 69, 381, 401))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_v1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_v1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_v1.setObjectName("horizontalLayout_v1")
        self.pushButton_run1 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_run1.setGeometry(QtCore.QRect(230, 480, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_run1.setFont(font)
        self.pushButton_run1.setStyleSheet("QPushButton#pushButton_run1{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_run1:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_run1:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_run1.setObjectName("pushButton_run1")
        self.horizontalLayout.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.frame_2)
        self.widget_4.setObjectName("widget_4")
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setGeometry(QtCore.QRect(170, 10, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-image:url(:/icons/icons/vc.png)")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton_v2 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_v2.setGeometry(QtCore.QRect(50, 480, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_v2.setFont(font)
        self.pushButton_v2.setStyleSheet("QPushButton#pushButton_v2{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_v2:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_v2:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_v2.setObjectName("pushButton_v2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.widget_4)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 70, 381, 401))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_v2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_v2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_v2.setObjectName("horizontalLayout_v2")
        self.pushButton_run2 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_run2.setGeometry(QtCore.QRect(230, 480, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_run2.setFont(font)
        self.pushButton_run2.setStyleSheet("QPushButton#pushButton_run2{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_run2:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_run2:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_run2.setObjectName("pushButton_run2")
        self.horizontalLayout.addWidget(self.widget_4)
        self.widget_2 = QtWidgets.QWidget(self.frame_2)
        self.widget_2.setEnabled(True)
        self.widget_2.setObjectName("widget_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(170, 10, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-image:url(:/icons/icons/two.png)")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.pushButton_v3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_v3.setGeometry(QtCore.QRect(50, 480, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_v3.setFont(font)
        self.pushButton_v3.setStyleSheet("QPushButton#pushButton_v3{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_v3:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_v3:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_v3.setObjectName("pushButton_v3")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.widget_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 70, 381, 401))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_v3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_v3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_v3.setObjectName("horizontalLayout_v3")
        self.pushButton_run3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_run3.setGeometry(QtCore.QRect(230, 480, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_run3.setFont(font)
        self.pushButton_run3.setStyleSheet("QPushButton#pushButton_run3{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_run3:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_run3:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_run3.setObjectName("pushButton_run3")
        self.horizontalLayout.addWidget(self.widget_2)
        self.stackedWidget.addWidget(self.page_main)
        self.page_change = QtWidgets.QWidget()
        self.page_change.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.page_change.setObjectName("page_change")
        self.lineEdit_pass = QtWidgets.QLineEdit(self.page_change)
        self.lineEdit_pass.setGeometry(QtCore.QRect(460, 80, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_pass.setFont(font)
        self.lineEdit_pass.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-radius:7px;\n"
"border-color: rgb(0, 0, 0);")
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.lineEdit_newpass1 = QtWidgets.QLineEdit(self.page_change)
        self.lineEdit_newpass1.setGeometry(QtCore.QRect(460, 210, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_newpass1.setFont(font)
        self.lineEdit_newpass1.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-radius:7px;\n"
"border-color: rgb(0, 0, 0);")
        self.lineEdit_newpass1.setObjectName("lineEdit_newpass1")
        self.pushButton_change = QtWidgets.QPushButton(self.page_change)
        self.pushButton_change.setGeometry(QtCore.QRect(550, 460, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_change.setFont(font)
        self.pushButton_change.setStyleSheet("QPushButton#pushButton_change{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_change:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_change:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_change.setObjectName("pushButton_change")
        self.lineEdit_newpass2 = QtWidgets.QLineEdit(self.page_change)
        self.lineEdit_newpass2.setGeometry(QtCore.QRect(460, 340, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_newpass2.setFont(font)
        self.lineEdit_newpass2.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-radius:7px;\n"
"border-color: rgb(0, 0, 0);")
        self.lineEdit_newpass2.setObjectName("lineEdit_newpass2")
        self.stackedWidget.addWidget(self.page_change)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("background-color: rgb(86, 88, 93);\n"
"border-bottom-left-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton_start = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_start.setGeometry(QtCore.QRect(960, 20, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet("QPushButton#pushButton_start{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_start:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_start:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_decode = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_decode.setGeometry(QtCore.QRect(20, 10, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_decode.setFont(font)
        self.pushButton_decode.setStyleSheet("QPushButton#pushButton_decode{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_decode:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_decode:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_decode.setObjectName("pushButton_decode")
        self.pushButton_vc = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_vc.setGeometry(QtCore.QRect(160, 10, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_vc.setFont(font)
        self.pushButton_vc.setStyleSheet("QPushButton#pushButton_vc{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_vc:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_vc:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_vc.setObjectName("pushButton_vc")
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 12)
        self.verticalLayout.setStretch(2, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_1.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_2.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_v1.setText(_translate("MainWindow", "进入"))
        self.pushButton_run1.setText(_translate("MainWindow", "开始"))
        self.pushButton_v2.setText(_translate("MainWindow", "进入"))
        self.pushButton_run2.setText(_translate("MainWindow", "开始"))
        self.pushButton_v3.setText(_translate("MainWindow", "进入"))
        self.pushButton_run3.setText(_translate("MainWindow", "开始"))
        self.lineEdit_pass.setPlaceholderText(_translate("MainWindow", "原密码："))
        self.lineEdit_newpass1.setPlaceholderText(_translate("MainWindow", "新密码："))
        self.pushButton_change.setText(_translate("MainWindow", "确定"))
        self.lineEdit_newpass2.setPlaceholderText(_translate("MainWindow", "确认新密码："))
        self.pushButton_start.setText(_translate("MainWindow", "运行"))
        self.pushButton_decode.setText(_translate("MainWindow", "更改密码"))
        self.pushButton_vc.setText(_translate("MainWindow", "返回主页面"))
import resource_rc
