# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2pro(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 631)
        MainWindow.setMinimumSize(QtCore.QSize(1400, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(1900, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setStyleSheet("#pushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_10.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"    border:none;\n"
"}\n"
"QPushButton#pushButton_2:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_10.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setStyleSheet("#pushButton_3{\n"
"    border:none;\n"
"}\n"
"QPushButton#pushButton_3:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/simui-minmax.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_10.addWidget(self.pushButton_3)
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setStyleSheet("#pushButton_1{\n"
"    border:none;\n"
"}\n"
"QPushButton#pushButton_1:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.pushButton_1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_1.setIcon(icon3)
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout_10.addWidget(self.pushButton_1)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.page.setObjectName("page")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(-1, -1, 9, -1)
        self.gridLayout_4.setHorizontalSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_ch_decode = QtWidgets.QPushButton(self.page)
        self.pushButton_ch_decode.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_ch_decode.setFont(font)
        self.pushButton_ch_decode.setStyleSheet("QPushButton#pushButton_ch_decode{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_ch_decode:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_ch_decode:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_ch_decode.setObjectName("pushButton_ch_decode")
        self.gridLayout_4.addWidget(self.pushButton_ch_decode, 6, 1, 1, 1)
        self.pushButton_record = QtWidgets.QPushButton(self.page)
        self.pushButton_record.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_record.setFont(font)
        self.pushButton_record.setStyleSheet("QPushButton#pushButton_record{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_record:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_record:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_record.setObjectName("pushButton_record")
        self.gridLayout_4.addWidget(self.pushButton_record, 5, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem2, 8, 1, 1, 1)
        self.pushButton_v2 = QtWidgets.QPushButton(self.page)
        self.pushButton_v2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_v2.setFont(font)
        self.pushButton_v2.setStyleSheet("QPushButton#pushButton_v2{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_v2:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_v2:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_v2.setObjectName("pushButton_v2")
        self.gridLayout_4.addWidget(self.pushButton_v2, 2, 1, 1, 1)
        self.pushButton_v1 = QtWidgets.QPushButton(self.page)
        self.pushButton_v1.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_v1.setFont(font)
        self.pushButton_v1.setStyleSheet("QPushButton#pushButton_v1{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_v1:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_v1:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_v1.setObjectName("pushButton_v1")
        self.gridLayout_4.addWidget(self.pushButton_v1, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem3, 0, 1, 1, 1)
        self.pushButton_v3 = QtWidgets.QPushButton(self.page)
        self.pushButton_v3.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_v3.setFont(font)
        self.pushButton_v3.setStyleSheet("QPushButton#pushButton_v3{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_v3:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_v3:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_v3.setObjectName("pushButton_v3")
        self.gridLayout_4.addWidget(self.pushButton_v3, 3, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 1, 2, 1, 1)
        self.pushButton_manage = QtWidgets.QPushButton(self.page)
        self.pushButton_manage.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_manage.setFont(font)
        self.pushButton_manage.setStyleSheet("QPushButton#pushButton_manage{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_manage:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_manage:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_manage.setObjectName("pushButton_manage")
        self.gridLayout_4.addWidget(self.pushButton_manage, 7, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem5, 4, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_v2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_v2.setObjectName("horizontalLayout_v2")
        self.label_v2 = QtWidgets.QLabel(self.page)
        self.label_v2.setText("")
        self.label_v2.setObjectName("label_v2")
        self.horizontalLayout_v2.addWidget(self.label_v2)
        self.gridLayout.addLayout(self.horizontalLayout_v2, 0, 1, 1, 1)
        self.horizontalLayout_v1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_v1.setObjectName("horizontalLayout_v1")
        self.label_v1 = QtWidgets.QLabel(self.page)
        self.label_v1.setText("")
        self.label_v1.setObjectName("label_v1")
        self.horizontalLayout_v1.addWidget(self.label_v1)
        self.gridLayout.addLayout(self.horizontalLayout_v1, 0, 0, 1, 1)
        self.horizontalLayout_v3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_v3.setObjectName("horizontalLayout_v3")
        self.label_v3 = QtWidgets.QLabel(self.page)
        self.label_v3.setText("")
        self.label_v3.setObjectName("label_v3")
        self.horizontalLayout_v3.addWidget(self.label_v3)
        self.gridLayout.addLayout(self.horizontalLayout_v3, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 8)
        self.gridLayout_11.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem6, 3, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem7, 1, 1, 1, 1)
        self.lineEdit_newpass1 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_newpass1.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_newpass1.setFont(font)
        self.lineEdit_newpass1.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-radius:7px;\n"
"border-color: rgb(0, 0, 0);")
        self.lineEdit_newpass1.setObjectName("lineEdit_newpass1")
        self.gridLayout_12.addWidget(self.lineEdit_newpass1, 2, 1, 1, 1)
        self.lineEdit_newpass2 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_newpass2.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_newpass2.setFont(font)
        self.lineEdit_newpass2.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-radius:7px;\n"
"border-color: rgb(0, 0, 0);")
        self.lineEdit_newpass2.setObjectName("lineEdit_newpass2")
        self.gridLayout_12.addWidget(self.lineEdit_newpass2, 4, 1, 1, 1)
        self.lineEdit_pass = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_pass.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_pass.setFont(font)
        self.lineEdit_pass.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-radius:7px;\n"
"border-color: rgb(0, 0, 0);")
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.gridLayout_12.addWidget(self.lineEdit_pass, 0, 1, 1, 1)
        self.pushButton_change = QtWidgets.QPushButton(self.page_2)
        self.pushButton_change.setMinimumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_change.setFont(font)
        self.pushButton_change.setStyleSheet("QPushButton#pushButton_change{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_change:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_change:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_change.setObjectName("pushButton_change")
        self.gridLayout_12.addWidget(self.pushButton_change, 6, 1, 1, 1)
        self.pushButton_return1 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_return1.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_return1.setFont(font)
        self.pushButton_return1.setStyleSheet("QPushButton#pushButton_return1{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_return1:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_return1:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_return1.setObjectName("pushButton_return1")
        self.gridLayout_12.addWidget(self.pushButton_return1, 6, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem8, 0, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem9, 5, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(360, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem10, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(160, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem11, 0, 2, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setStyleSheet("background-color: rgb(140, 140, 140);")
        self.page_3.setObjectName("page_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem12 = QtWidgets.QSpacerItem(125, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem12, 0, 0, 1, 1)
        self.pushButton_register = QtWidgets.QPushButton(self.page_3)
        self.pushButton_register.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_register.setFont(font)
        self.pushButton_register.setStyleSheet("QPushButton#pushButton_register{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_register:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_register:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_register.setObjectName("pushButton_register")
        self.gridLayout_6.addWidget(self.pushButton_register, 0, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(125, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem13, 0, 2, 1, 1)
        self.pushButton_find = QtWidgets.QPushButton(self.page_3)
        self.pushButton_find.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_find.setFont(font)
        self.pushButton_find.setStyleSheet("QPushButton#pushButton_find{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_find:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_find:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_find.setObjectName("pushButton_find")
        self.gridLayout_6.addWidget(self.pushButton_find, 1, 1, 1, 1)
        self.pushButton_delete = QtWidgets.QPushButton(self.page_3)
        self.pushButton_delete.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setStyleSheet("QPushButton#pushButton_delete{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_delete:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_delete:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.gridLayout_6.addWidget(self.pushButton_delete, 2, 1, 1, 1)
        self.pushButton_return = QtWidgets.QPushButton(self.page_3)
        self.pushButton_return.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_return.setFont(font)
        self.pushButton_return.setStyleSheet("QPushButton#pushButton_return{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_return:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_return:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_return.setObjectName("pushButton_return")
        self.gridLayout_6.addWidget(self.pushButton_return, 3, 1, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.stackedWidget_2.setFont(font)
        self.stackedWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_register = QtWidgets.QWidget()
        self.page_register.setObjectName("page_register")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_register)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem14 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem14, 0, 0, 1, 1)
        self.lineEdit_register = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_register.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_register.setFont(font)
        self.lineEdit_register.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-radius:7px;\n"
"border-color: rgb(0, 0, 0);")
        self.lineEdit_register.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_register.setObjectName("lineEdit_register")
        self.gridLayout_8.addWidget(self.lineEdit_register, 0, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem15, 0, 2, 1, 1)
        self.lineEdit_decode = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_decode.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_decode.setFont(font)
        self.lineEdit_decode.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-radius:7px;\n"
"border-color: rgb(0, 0, 0);")
        self.lineEdit_decode.setObjectName("lineEdit_decode")
        self.gridLayout_8.addWidget(self.lineEdit_decode, 1, 1, 1, 1)
        self.pushButton_affirmregister = QtWidgets.QPushButton(self.page_register)
        self.pushButton_affirmregister.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_affirmregister.setFont(font)
        self.pushButton_affirmregister.setStyleSheet("QPushButton#pushButton_affirmregister{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_affirmregister:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_affirmregister:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_affirmregister.setObjectName("pushButton_affirmregister")
        self.gridLayout_8.addWidget(self.pushButton_affirmregister, 3, 1, 1, 1)
        self.lineEdit_AffirmDecode = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_AffirmDecode.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_AffirmDecode.setFont(font)
        self.lineEdit_AffirmDecode.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-radius:7px;\n"
"border-color: rgb(0, 0, 0);")
        self.lineEdit_AffirmDecode.setObjectName("lineEdit_AffirmDecode")
        self.gridLayout_8.addWidget(self.lineEdit_AffirmDecode, 2, 1, 1, 1)
        self.stackedWidget_2.addWidget(self.page_register)
        self.page_find = QtWidgets.QWidget()
        self.page_find.setObjectName("page_find")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_find)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem16 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem16, 0, 2, 1, 1)
        self.lineEdit_find = QtWidgets.QLineEdit(self.page_find)
        self.lineEdit_find.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_find.setFont(font)
        self.lineEdit_find.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-radius:7px;\n"
"border-color: rgb(0, 0, 0);")
        self.lineEdit_find.setObjectName("lineEdit_find")
        self.gridLayout_10.addWidget(self.lineEdit_find, 0, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem17, 0, 0, 1, 1)
        self.pushButton_affirmfind = QtWidgets.QPushButton(self.page_find)
        self.pushButton_affirmfind.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_affirmfind.setFont(font)
        self.pushButton_affirmfind.setStyleSheet("QPushButton#pushButton_affirmfind{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_affirmfind:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_affirmfind:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_affirmfind.setObjectName("pushButton_affirmfind")
        self.gridLayout_10.addWidget(self.pushButton_affirmfind, 2, 1, 1, 1)
        self.textBrowser_find = QtWidgets.QTextBrowser(self.page_find)
        self.textBrowser_find.setObjectName("textBrowser_find")
        self.gridLayout_10.addWidget(self.textBrowser_find, 4, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_10.addItem(spacerItem18, 1, 1, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_10.addItem(spacerItem19, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.page_find)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_10.addWidget(self.label_5, 4, 0, 1, 1)
        self.pushButton_affirmall = QtWidgets.QPushButton(self.page_find)
        self.pushButton_affirmall.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_affirmall.setFont(font)
        self.pushButton_affirmall.setStyleSheet("QPushButton#pushButton_affirmall{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_affirmall:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_affirmall:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_affirmall.setObjectName("pushButton_affirmall")
        self.gridLayout_10.addWidget(self.pushButton_affirmall, 4, 2, 1, 1)
        self.stackedWidget_2.addWidget(self.page_find)
        self.page_delete = QtWidgets.QWidget()
        self.page_delete.setObjectName("page_delete")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.page_delete)
        self.gridLayout_9.setContentsMargins(9, 9, 9, 6)
        self.gridLayout_9.setHorizontalSpacing(6)
        self.gridLayout_9.setVerticalSpacing(9)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pushButton_affirmdelete = QtWidgets.QPushButton(self.page_delete)
        self.pushButton_affirmdelete.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_affirmdelete.setFont(font)
        self.pushButton_affirmdelete.setStyleSheet("QPushButton#pushButton_affirmdelete{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_affirmdelete:hover{\n"
"background-color:rgba(2,65,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_affirmdelete:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"}")
        self.pushButton_affirmdelete.setObjectName("pushButton_affirmdelete")
        self.gridLayout_9.addWidget(self.pushButton_affirmdelete, 3, 1, 1, 1)
        self.lineEdit_delete = QtWidgets.QLineEdit(self.page_delete)
        self.lineEdit_delete.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_delete.setFont(font)
        self.lineEdit_delete.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-radius:7px;\n"
"border-color: rgb(0, 0, 0);")
        self.lineEdit_delete.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_delete.setObjectName("lineEdit_delete")
        self.gridLayout_9.addWidget(self.lineEdit_delete, 0, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem20, 0, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem21, 0, 2, 1, 1)
        self.lineEdit_managedecode = QtWidgets.QLineEdit(self.page_delete)
        self.lineEdit_managedecode.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_managedecode.setFont(font)
        self.lineEdit_managedecode.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-radius:7px;\n"
"border-color: rgb(0, 0, 0);")
        self.lineEdit_managedecode.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_managedecode.setObjectName("lineEdit_managedecode")
        self.gridLayout_9.addWidget(self.lineEdit_managedecode, 2, 1, 1, 1)
        self.lineEdit_affirmdelete = QtWidgets.QLineEdit(self.page_delete)
        self.lineEdit_affirmdelete.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_affirmdelete.setFont(font)
        self.lineEdit_affirmdelete.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-radius:7px;\n"
"border-color: rgb(0, 0, 0);")
        self.lineEdit_affirmdelete.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_affirmdelete.setObjectName("lineEdit_affirmdelete")
        self.gridLayout_9.addWidget(self.lineEdit_affirmdelete, 1, 1, 1, 1)
        self.textBrowser_delete = QtWidgets.QTextBrowser(self.page_delete)
        self.textBrowser_delete.setObjectName("textBrowser_delete")
        self.gridLayout_9.addWidget(self.textBrowser_delete, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page_delete)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 4, 0, 1, 1)
        self.gridLayout_9.setRowStretch(0, 1)
        self.stackedWidget_2.addWidget(self.page_delete)
        self.horizontalLayout_11.addWidget(self.stackedWidget_2)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_7.setStretch(0, 4)
        self.horizontalLayout_7.setStretch(1, 6)
        self.gridLayout_5.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 9)
        self.gridLayout_7.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(2)
        self.pushButton_1.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_2.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_ch_decode.setText(_translate("MainWindow", "更改密码"))
        self.pushButton_record.setText(_translate("MainWindow", "记录"))
        self.pushButton_v2.setText(_translate("MainWindow", "105B罐"))
        self.pushButton_v1.setText(_translate("MainWindow", "105A罐"))
        self.pushButton_v3.setText(_translate("MainWindow", "102罐"))
        self.pushButton_manage.setText(_translate("MainWindow", "管理员"))
        self.lineEdit_newpass1.setPlaceholderText(_translate("MainWindow", "新密码："))
        self.lineEdit_newpass2.setPlaceholderText(_translate("MainWindow", "确认新密码："))
        self.lineEdit_pass.setPlaceholderText(_translate("MainWindow", "原密码："))
        self.pushButton_change.setText(_translate("MainWindow", "确定"))
        self.pushButton_return1.setText(_translate("MainWindow", "返回"))
        self.pushButton_register.setText(_translate("MainWindow", "注册"))
        self.pushButton_find.setText(_translate("MainWindow", "查找"))
        self.pushButton_delete.setText(_translate("MainWindow", "删除"))
        self.pushButton_return.setText(_translate("MainWindow", "返回"))
        self.lineEdit_register.setPlaceholderText(_translate("MainWindow", "输入账号："))
        self.lineEdit_decode.setPlaceholderText(_translate("MainWindow", "输入密码："))
        self.pushButton_affirmregister.setText(_translate("MainWindow", "注册"))
        self.lineEdit_AffirmDecode.setPlaceholderText(_translate("MainWindow", "确认密码："))
        self.lineEdit_find.setPlaceholderText(_translate("MainWindow", "输入账号："))
        self.pushButton_affirmfind.setText(_translate("MainWindow", "确定"))
        self.label_5.setText(_translate("MainWindow", "查找账号信息:"))
        self.pushButton_affirmall.setText(_translate("MainWindow", "查找所有用户"))
        self.pushButton_affirmdelete.setText(_translate("MainWindow", "确定删除"))
        self.lineEdit_delete.setPlaceholderText(_translate("MainWindow", "删除账号："))
        self.lineEdit_managedecode.setPlaceholderText(_translate("MainWindow", "管理员密码："))
        self.lineEdit_affirmdelete.setPlaceholderText(_translate("MainWindow", "确认账号："))
        self.label_4.setText(_translate("MainWindow", "删除账号信息:"))
import resource_rc
